SET DEFINE OFF

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Afghanistan ', 0);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Albania ', 1);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Algeria ', 2);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('American Samoa ', 3);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Andorra ', 4);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Angola ', 5);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Anguilla ', 6);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Antigua & Barbuda ', 7);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Argentina ', 8);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Armenia ', 9);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Aruba ', 10);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Australia ', 11);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Austria ', 12);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Azerbaijan ', 13);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Bahamas, The ', 14);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Bahrain ', 15);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Bangladesh ', 16);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Barbados ', 17);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Belarus ', 18);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Belgium ', 19);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Belize ', 20);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Benin ', 21);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Bermuda ', 22);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Bhutan ', 23);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Bolivia ', 24);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Bosnia & Herzegovina ', 25);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Botswana ', 26);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Brazil ', 27);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('British Virgin Is. ', 28);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Brunei ', 29);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Bulgaria ', 30);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Burkina Faso ', 31);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Burma ', 32);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Burundi ', 33);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Cambodia ', 34);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Cameroon ', 35);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Canada ', 36);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Cape Verde ', 37);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Cayman Islands ', 38);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Central African Rep. ', 39);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Chad ', 40);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Chile ', 41);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('China ', 42);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Colombia ', 43);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Comoros ', 44);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Congo, Dem. Rep. ', 45);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Congo, Repub. of the ', 46);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Cook Islands ', 47);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Costa Rica ', 48);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Cote d''Ivoire ', 49);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Croatia ', 50);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Cuba ', 51);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Cyprus ', 52);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Czech Republic ', 53);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Denmark ', 54);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Djibouti ', 55);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Dominica ', 56);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Dominican Republic ', 57);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('East Timor ', 58);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Ecuador ', 59);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Egypt ', 60);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('El Salvador ', 61);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Equatorial Guinea ', 62);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Eritrea ', 63);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Estonia ', 64);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Ethiopia ', 65);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Faroe Islands ', 66);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Fiji ', 67);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Finland ', 68);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('France ', 69);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('French Guiana ', 70);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('French Polynesia ', 71);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Gabon ', 72);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Gambia, The ', 73);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Gaza Strip ', 74);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Georgia ', 75);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Germany ', 76);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Ghana ', 77);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Gibraltar ', 78);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Greece ', 79);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Greenland ', 80);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Grenada ', 81);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Guadeloupe ', 82);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Guam ', 83);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Guatemala ', 84);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Guernsey ', 85);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Guinea ', 86);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Guinea-Bissau ', 87);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Guyana ', 88);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Haiti ', 89);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Honduras ', 90);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Hong Kong ', 91);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Hungary ', 92);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Iceland ', 93);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('India ', 94);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Indonesia ', 95);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Iran ', 96);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Iraq ', 97);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Ireland ', 98);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Isle of Man ', 99);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Israel ', 100);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Italy ', 101);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Jamaica ', 102);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Japan ', 103);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Jersey ', 104);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Jordan ', 105);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Kazakhstan ', 106);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Kenya ', 107);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Kiribati ', 108);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Korea, North ', 109);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Korea, South ', 110);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Kuwait ', 111);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Kyrgyzstan ', 112);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Laos ', 113);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Latvia ', 114);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Lebanon ', 115);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Lesotho ', 116);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Liberia ', 117);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Libya ', 118);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Liechtenstein ', 119);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Lithuania ', 120);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Luxembourg ', 121);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Macau ', 122);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Macedonia ', 123);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Madagascar ', 124);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Malawi ', 125);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Malaysia ', 126);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Maldives ', 127);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Mali ', 128);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Malta ', 129);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Marshall Islands ', 130);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Martinique ', 131);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Mauritania ', 132);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Mauritius ', 133);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Mayotte ', 134);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Mexico ', 135);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Micronesia, Fed. St. ', 136);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Moldova ', 137);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Monaco ', 138);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Mongolia ', 139);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Montserrat ', 140);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Morocco ', 141);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Mozambique ', 142);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Namibia ', 143);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Nauru ', 144);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Nepal ', 145);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Netherlands ', 146);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Netherlands Antilles ', 147);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('New Caledonia ', 148);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('New Zealand ', 149);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Nicaragua ', 150);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Niger ', 151);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Nigeria ', 152);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('N. Mariana Islands ', 153);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Norway ', 154);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Oman ', 155);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Pakistan ', 156);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Palau ', 157);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Panama ', 158);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Papua New Guinea ', 159);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Paraguay ', 160);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Peru ', 161);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Philippines ', 162);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Poland ', 163);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Portugal ', 164);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Puerto Rico ', 165);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Qatar ', 166);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Reunion ', 167);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Romania ', 168);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Russia ', 169);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Rwanda ', 170);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Saint Helena ', 171);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Saint Kitts & Nevis ', 172);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Saint Lucia ', 173);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('St Pierre & Miquelon ', 174);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Saint Vincent and the Grenadines ', 175);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Samoa ', 176);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('San Marino ', 177);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Sao Tome & Principe ', 178);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Saudi Arabia ', 179);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Senegal ', 180);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Serbia ', 181);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Seychelles ', 182);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Sierra Leone ', 183);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Singapore ', 184);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Slovakia ', 185);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Slovenia ', 186);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Solomon Islands ', 187);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Somalia ', 188);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('South Africa ', 189);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Spain ', 190);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Sri Lanka ', 191);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Sudan ', 192);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Suriname ', 193);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Swaziland ', 194);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Sweden ', 195);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Switzerland ', 196);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Syria ', 197);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Taiwan ', 198);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Tajikistan ', 199);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Tanzania ', 200);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Thailand ', 201);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Togo ', 202);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Tonga ', 203);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Trinidad & Tobago ', 204);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Tunisia ', 205);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Turkey ', 206);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Turkmenistan ', 207);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Turks & Caicos Is ', 208);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Tuvalu ', 209);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Uganda ', 210);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Ukraine ', 211);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('United Arab Emirates ', 212);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('United Kingdom ', 213);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('United States ', 214);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Uruguay ', 215);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Uzbekistan ', 216);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Vanuatu ', 217);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Venezuela ', 218);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Vietnam ', 219);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Virgin Islands ', 220);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Wallis and Futuna ', 221);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('West Bank ', 222);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Western Sahara ', 223);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Yemen ', 224);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Zambia ', 225);

INSERT INTO COUNTRIES (NAME, COUNTRY_ID) 
VALUES ('Zimbabwe ', 226);

