SET DEFINE OFF

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Emirates Stadium', 45, 46);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('The City Ground', 138, 165);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Ashton Gate', 6, 70);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Amex Stadium', 4, 171);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('DW Stadium', 40, 3);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Carrow Road', 28, 147);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Ochilview Park', 97, 118);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('New Douglas Park', 92, 143);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Newry Showgrounds', 95, 109);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Ballymena Showgrounds', 8, 18);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Bescot Stadium', 13, 74);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('KC Stadium', 71, 134);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('The Hive Stadium', 144, 184);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Glebe Park', 59, 208);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Tynecastle', 151, 101);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Stangmore Park', 132, 57);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('The Dub', 141, 183);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Griffin Park', 62, 159);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Inver Park', 69, 140);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Gayfield Park', 56, 223);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Pittodrie', 101, 211);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('The Galpharm Stadium', 142, 153);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Edgar Street', 43, 22);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Brisbane Road', 21, 164);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Recreation Park', 108, 21);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Molineux', 88, 83);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Oakwell', 96, 91);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Crown Ground', 34, 4);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Central Park', 30, 197);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Goodison Park', 61, 37);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Prenton Park', 104, 2);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Wembley', 160, 223);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Britannia Stadium', 22, 157);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Meadow Lane', 84, 202);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('The Oval', 146, 150);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Cliftonhill', 31, 106);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Field Mill', 50, 16);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Stamford Bridge', 131, 165);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Kenilworth Road', 73, 135);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Madjeski Stadium', 82, 170);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Seaview', 114, 175);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Etihad Stadium', 46, 185);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Easter Road', 42, 101);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Kingsmeadow', 75, 132);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Huish Park', 67, 2);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Solitude', 120, 13);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Stark''s Park', 133, 162);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Milltown', 87, 211);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Fratton Park', 54, 63);

INSERT INTO STADIUMS (NAME, STADIUM_ID, COUNTRY_ID) 
VALUES ('Shielfield Park', 118, 8);

