SET DEFINE OFF

INSERT INTO LEAGUES (NAME, LEAGUE_ID) 
VALUES ('Premier League', 0);

INSERT INTO LEAGUES (NAME, LEAGUE_ID) 
VALUES ('Bundesliga', 1);

INSERT INTO LEAGUES (NAME, LEAGUE_ID) 
VALUES ('Ligue 1', 2);

INSERT INTO LEAGUES (NAME, LEAGUE_ID) 
VALUES ('LaLiga', 3);

INSERT INTO LEAGUES (NAME, LEAGUE_ID) 
VALUES ('Serie A', 4);

