SET DEFINE OFF

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Manchester City', 0, 'MAN', 97);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Bayern Munich', 1, 'BAY', 195);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Paris Saint-Germain', 2, 'PAR', 198);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Barcelona', 3, 'BAR', 219);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Real Madrid', 4, 'REA', 28);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Manchester United', 5, 'MAN', 42);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Juventus', 6, 'JUV', 21);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Aston Villa', 7, 'AST', 151);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Borussia Dortmund', 8, 'BOR', 60);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Atletico Madrid', 9, 'ATL', 121);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Atalanta', 10, 'ATA', 25);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Chelsea', 11, 'CHE', 10);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Liverpool', 12, 'LIV', 28);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('AC Milan', 13, 'AC ', 44);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Lille', 14, 'LIL', 74);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Tottenham', 15, 'TOT', 0);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Napoli', 16, 'NAP', 220);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Leicester', 17, 'LEI', 47);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Wolfsburg', 18, 'WOL', 145);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Inter', 19, 'INT', 85);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Lyon', 20, 'LYO', 31);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('RB Leipzig', 21, 'RB ', 67);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Leeds', 22, 'LEE', 57);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('West Ham', 23, 'WES', 36);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Everton', 24, 'EVE', 100);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Bayer Leverkusen', 25, 'BAY', 115);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Eintracht Frankfurt', 26, 'EIN', 18);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Monaco', 27, 'MON', 124);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Roma', 28, 'ROM', 171);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Sevilla', 29, 'SEV', 46);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Borussia M.Gladbach', 30, 'BOR', 185);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Arsenal', 31, 'ARS', 159);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Rennes', 32, 'REN', 32);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('VfB Stuttgart', 33, 'VFB', 202);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Wolverhampton Wanderers', 34, 'WOL', 128);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Sassuolo', 35, 'SAS', 92);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Metz', 36, 'MET', 203);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Villarreal', 37, 'VIL', 47);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Real Sociedad', 38, 'REA', 123);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Brighton', 39, 'BRI', 224);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Real Betis', 40, 'REA', 23);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Burnley', 41, 'BUR', 164);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Lens', 42, 'LEN', 57);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Brest', 43, 'BRE', 10);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Fulham', 44, 'FUL', 214);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Marseille', 45, 'MAR', 90);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Sampdoria', 46, 'SAM', 217);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Montpellier', 47, 'MON', 21);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Nice', 48, 'NIC', 28);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Hoffenheim', 49, 'HOF', 153);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Southampton', 50, 'SOU', 58);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Newcastle United', 51, 'NEW', 55);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Lazio', 52, 'LAZ', 129);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Nantes', 53, 'NAN', 157);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Union Berlin', 54, 'UNI', 158);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Strasbourg', 55, 'STR', 65);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Crystal Palace', 56, 'CRY', 23);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Freiburg', 57, 'FRE', 71);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Valencia', 58, 'VAL', 56);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Celta Vigo', 59, 'CEL', 156);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Reims', 60, 'REI', 152);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Torino', 61, 'TOR', 82);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Verona', 62, 'VER', 147);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Saint-Etienne', 63, 'SAI', 99);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Bordeaux', 64, 'BOR', 170);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Hertha Berlin', 65, 'HER', 136);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Cagliari', 66, 'CAG', 104);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Mainz 05', 67, 'MAI', 7);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Bologna', 68, 'BOL', 63);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Augsburg', 69, 'AUG', 155);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Udinese', 70, 'UDI', 166);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('SD Huesca', 71, 'SD ', 67);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Athletic Bilbao', 72, 'ATH', 78);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Osasuna', 73, 'OSA', 77);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Lorient', 74, 'LOR', 112);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Genoa', 75, 'GEN', 61);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Arminia Bielefeld', 76, 'ARM', 83);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Angers', 77, 'ANG', 16);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Eibar', 78, 'EIB', 190);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Werder Bremen', 79, 'WER', 172);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Fiorentina', 80, 'FIO', 124);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Nimes', 81, 'NIM', 123);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('West Bromwich Albion', 82, 'WES', 73);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('FC Koln', 83, 'FC ', 90);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Deportivo Alaves', 84, 'DEP', 46);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Levante', 85, 'LEV', 3);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Spezia', 86, 'SPE', 225);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Getafe', 87, 'GET', 155);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Parma Calcio 1913', 88, 'PAR', 98);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Elche', 89, 'ELC', 19);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Granada', 90, 'GRA', 76);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Cadiz', 91, 'CAD', 118);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Real Valladolid', 92, 'REA', 214);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Sheffield United', 93, 'SHE', 126);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Crotone', 94, 'CRO', 60);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Benevento', 95, 'BEN', 152);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Dijon', 96, 'DIJ', 107);

INSERT INTO TEAMS (NAME, TEAM_ID, ACRONYM, COUNTRY_ID) 
VALUES ('Schalke 04', 97, 'SCH', 97);

