SET DEFINE OFF

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (0, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (1, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (2, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (3, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (4, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (5, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (6, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (7, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (8, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (9, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (10, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (11, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (12, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (13, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (14, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (15, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (16, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (17, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (18, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (19, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (20, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (21, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (22, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (23, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (24, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (25, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (26, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (27, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (28, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (29, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (30, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (31, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (32, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (33, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (34, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (35, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (36, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (37, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (38, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (39, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (40, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (41, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (42, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (43, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (44, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (45, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (46, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (47, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (48, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (49, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (50, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (51, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (52, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (53, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (54, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (55, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (56, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (57, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (58, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (59, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (60, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (61, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (62, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (63, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (64, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (65, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (66, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (67, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (68, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (69, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (70, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (71, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (72, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (73, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (74, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (75, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (76, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (77, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (78, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (79, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (80, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (81, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (82, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (83, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (84, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (85, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (86, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (87, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (88, 2);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (89, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (90, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (91, 3);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (92, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (93, 4);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (94, 1);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (95, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (96, 0);

INSERT INTO TEAM_PLAYS_IN_LEAGUE (TEAM_ID, LEAGUE_ID) 
VALUES (97, 2);

